### PR TITLE
fix typo in -funwind-tables for expat

### PR DESCRIPTION
**Pull request by risto3**
pull request for typo in expat

### CODE REVIEW

**Comment by risto3** [comment]
btw, what *was* the motivation to change the default in the first place?

**Comment by danmcd** [comment]
It goes back well before my time:

commit 07d4e227de43d31ca2c6dd59363d0963baf753dc
Author: Theo Schlossnagle <jesus@omniti.com>
Date:   Wed Apr 3 03:51:17 2013 +0000

    unwind-table instead of exceptions

**Comment by postwait** [comment]
This made things play nicer with luajit.

**Comment by risto3** [comment]
Is this http://lua-users.org/lists/lua-l/2011-06/msg00431.html ?
if so, you may wish to try what I've been using from Rich Lowe's gcc work for quite a while now in my pkgsrc branch for gcc4[7-9]... namely the crtbeginS and crtendS bits for shared ... that calmed most things down for me as far as I can tell once I enabled eh_frame_hdrs *and* __cxa_atexit... (can't say I've specifically tried luajit though, btw where is it in omnios-build?)

**Comment by danmcd** [comment]
luajit isn't in omnios-build.  It MIGHT be in ms.omniti.com.  I also know that postwait uses luajit for Circonus-related work.

**Pull request merged**
