### PR TITLE
ntp wait_for_sync should be more configurable #89

### PR DESCRIPTION
**Pull request by andy-js**

### CODE REVIEW

**Comment by danmcd** [comment]
Please document here the tests you performed.  Your change seems good, but I don't want to have OOod or post-upgrade NTP surprising me.

**Comment by andy-js** [comment]
I installed the manifest and method files into the appropriate places and imported the manifest with "svccfg import".  I put some unreachable servers in my ntp.conf file and tried several different values for wait_for_sync_tries and wait_for_sync_delay (set using "svccfg setprop") to observe the effect.

Even with these changes the start method will timeout long before ntp-wait does so nobody should see any change in behaviour there.  The only possible exception is the lower sleep time, which I guess makes it more likely for a sync to happen over an unstable connection.

**Comment by andy-js** [comment]
wait_for_sync is also disabled by default.  If you don't use it these changes don't make any difference.

**Comment by danmcd** [comment]
Thank you.

**Pull request merged**
