### PR TITLE
add bmake-20160926

### PR DESCRIPTION
**Pull request by lotheac**

### CODE REVIEW

**Comment by danmcd** [comment]
Tarball source for mirrors.omniti.com?

**Comment by lotheac** [comment]
On Tue, Nov 22 2016 08:49:33 -0800, Dan McDonald wrote:
> Tarball source for mirrors.omniti.com?

http://www.crufty.net/ftp/pub/sjg/

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by danmcd** [comment]
Needs a local.mog file.  I can add one if you wish...

> The file to be installed in usr/share/mk/meta2deps.py does not specify a specific version of python either in its installed path nor in its text.  Such a file cannot be analyzed for dependencies since the version of python it will be used with is unknown.  The text of the file is here: /tmp/build_danmcd/developer_bmake_pkg/usr/share/mk/meta2deps.py.

**Comment by lotheac** [comment]
On Tue, Nov 22 2016 10:27:04 -0800, Dan McDonald wrote:
> Needs a local.mog file.  I can add one if you wish...

Sure, go ahead.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by danmcd** [comment]
Closing PR, but pushing this commit (with local.mog).

**Comment by danmcd** [comment]
https://github.com/omniti-labs/omnios-build/commit/bb130af5d05e81801ceb505cb9e4e25620aaec2a

**Pull request closed without merging**
